### ISSUE TITLE
Snap install doesn't seem to work

### ISSUE THREAD

**Issue by nschonni** [caarlos0/jsonfmt#4]
Because it's a command line tool, it needs probably needs access outside it's own restricted directory.
Looks like you can request a review for "classic" access https://snapcraft.io/docs/choosing-a-security-model or the interfaces need to be requested https://snapcraft.io/docs/snap-confinement

**Comment by caarlos0** [comment]
yeah, this snap thing is a mess, more likely I'll just stop releasing snaps as this classic confinement takes ages anyway
